# Generated by Django 3.1.3 on 2020-12-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measuring_units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuring_unit_name', models.CharField(max_length=50, unique=True)),
                ('measuring_unit_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
