# Generated by Django 3.1.3 on 2020-12-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
