# Generated by Django 3.1.3 on 2020-12-30 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_remove_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.country'),
        ),
    ]
