# Generated by Django 3.1.3 on 2020-12-30 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_auto_20201230_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.country')),
            ],
        ),
    ]
