# Generated by Django 3.1.3 on 2020-12-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_code',
        ),
    ]
