# Generated by Django 3.1.3 on 2020-12-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_remove_company_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(default='GPL', max_length=30),
        ),
    ]
