# Generated by Django 3.1.3 on 2020-12-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_plant_plant_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measuring_units',
            new_name='MeasuringUnits',
        ),
    ]
