# Generated by Django 3.1.3 on 2020-12-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_auto_20201230_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_code',
            field=models.CharField(max_length=30),
        ),
    ]
